import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata = {
  title: "Terms of Service - Sociova",
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-16">
        <Button render={<a href="/" />} nativeButton={false} variant="ghost" className="mb-8 text-muted-foreground">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Home
        </Button>

        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-muted-foreground mb-12">
          Last updated: March 12, 2026
        </p>

        <div className="prose prose-invert prose-sm max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing and using Sociova, you accept and agree to be bound by these Terms
              of Service. If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Sociova provides social media management tools including AI-powered content
              generation, post scheduling, automatic publishing, and analytics for Twitter accounts.
              We reserve the right to modify or discontinue features at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. User Accounts</h2>
            <p className="text-muted-foreground leading-relaxed">
              You are responsible for maintaining the security of your account and all activities that
              occur under your account. You must provide accurate and complete information when
              creating your account. You must not use the service for any illegal or unauthorized
              purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to use Sociova to post spam, harassment, hate speech, or any content
              that violates Twitter&apos;s terms of service. You are solely responsible for the content
              you create and publish through our platform. Automated posting must comply with
              Twitter&apos;s API rate limits and automation rules.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Subscription and Billing</h2>
            <p className="text-muted-foreground leading-relaxed">
              Paid features require a subscription. Subscriptions are billed monthly or annually based
              on your chosen plan. You may cancel at any time, and your access will continue until the
              end of the current billing period. Refunds are handled on a case-by-case basis.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. AI-Generated Content</h2>
            <p className="text-muted-foreground leading-relaxed">
              Content generated by our AI tools is provided as suggestions. You are responsible for
              reviewing and approving all content before it is published. Sociova is not
              responsible for any consequences resulting from publishing AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              Sociova is provided &quot;as is&quot; without warranties of any kind. We are not
              liable for any damages arising from the use of our service, including but not limited to
              missed posts, account suspensions, or data loss. Our total liability shall not exceed the
              amount paid by you in the preceding 12 months.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to update these terms at any time. Continued use of the service
              after changes constitutes acceptance of the new terms. We will notify users of material
              changes via email or in-app notification.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              For questions about these Terms of Service, contact us at legal@sociova.com.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
